-- ============================================
-- SISTEM AKUNTANSI PENDAPATAN DAN PIUTANG WO
-- ============================================


-- Hapus tabel lama jika ada
DROP TABLE IF EXISTS pembayaran CASCADE;
DROP TABLE IF EXISTS transaksi_wedding CASCADE;
DROP TABLE IF EXISTS paket_wedding CASCADE;
DROP TABLE IF EXISTS pelanggan CASCADE;


-- ============================================
-- 1. TABEL PELANGGAN
-- ============================================

CREATE TABLE pelanggan (
    id_pelanggan BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama_pelanggan VARCHAR(100) NOT NULL,
    no_hp VARCHAR(20),
    email VARCHAR(100),
    alamat TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);


-- ============================================
-- 2. TABEL PAKET WEDDING
-- ============================================

CREATE TABLE paket_wedding (
    id_paket BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama_paket VARCHAR(100) NOT NULL,
    deskripsi TEXT,
    harga_paket NUMERIC(15,2) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);


-- ============================================
-- 3. TABEL TRANSAKSI WEDDING
-- ============================================

CREATE TABLE transaksi_wedding (
    id_transaksi BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    id_pelanggan BIGINT NOT NULL,
    id_paket BIGINT NOT NULL,

    tanggal_transaksi DATE NOT NULL DEFAULT CURRENT_DATE,

    total_transaksi NUMERIC(15,2) NOT NULL,

    status_transaksi VARCHAR(30)
        NOT NULL DEFAULT 'Belum Lunas',

    created_at TIMESTAMPTZ DEFAULT NOW(),

    CONSTRAINT fk_transaksi_pelanggan
        FOREIGN KEY (id_pelanggan)
        REFERENCES pelanggan(id_pelanggan),

    CONSTRAINT fk_transaksi_paket
        FOREIGN KEY (id_paket)
        REFERENCES paket_wedding(id_paket)
);


-- ============================================
-- 4. TABEL PEMBAYARAN
-- ============================================

CREATE TABLE pembayaran (
    id_pembayaran BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    id_transaksi BIGINT NOT NULL,

    tanggal_bayar DATE NOT NULL DEFAULT CURRENT_DATE,

    jumlah_bayar NUMERIC(15,2) NOT NULL,

    metode_bayar VARCHAR(30) NOT NULL,

    keterangan TEXT,

    created_at TIMESTAMPTZ DEFAULT NOW(),

    CONSTRAINT fk_pembayaran_transaksi
        FOREIGN KEY (id_transaksi)
        REFERENCES transaksi_wedding(id_transaksi)
        ON DELETE CASCADE
);


-- ============================================
-- DATA AWAL PELANGGAN
-- ============================================

INSERT INTO pelanggan
(nama_pelanggan, no_hp, email, alamat)
VALUES
(
    'Andi Pratama',
    '081234567890',
    'andi@gmail.com',
    'Semarang'
),
(
    'Salsa Putri',
    '081298765432',
    'salsa@gmail.com',
    'Kendal'
),
(
    'Rizky Ramadhan',
    '081377788899',
    'rizky@gmail.com',
    'Demak'
);


-- ============================================
-- DATA AWAL PAKET
-- ============================================

INSERT INTO paket_wedding
(nama_paket, deskripsi, harga_paket)
VALUES
(
    'Silver',
    'Dekorasi dasar, catering dan dokumentasi.',
    25000000
),
(
    'Gold',
    'Dekorasi premium, catering, dokumentasi dan MC.',
    40000000
),
(
    'Platinum',
    'Paket lengkap dengan dekorasi premium, catering, dokumentasi, MC dan entertainment.',
    60000000
);


-- ============================================
-- DATA AWAL TRANSAKSI
-- ============================================

INSERT INTO transaksi_wedding
(
    id_pelanggan,
    id_paket,
    tanggal_transaksi,
    total_transaksi,
    status_transaksi
)
VALUES
(
    1,
    1,
    CURRENT_DATE,
    25000000,
    'Belum Lunas'
),
(
    2,
    2,
    CURRENT_DATE,
    40000000,
    'Belum Lunas'
),
(
    3,
    3,
    CURRENT_DATE,
    60000000,
    'Belum Lunas'
);


-- ============================================
-- DATA AWAL PEMBAYARAN
-- ============================================

INSERT INTO pembayaran
(
    id_transaksi,
    tanggal_bayar,
    jumlah_bayar,
    metode_bayar,
    keterangan
)
VALUES
(
    1,
    CURRENT_DATE,
    10000000,
    'Transfer',
    'DP'
),
(
    2,
    CURRENT_DATE,
    15000000,
    'Transfer',
    'DP'
),
(
    3,
    CURRENT_DATE,
    30000000,
    'Transfer',
    'DP'
);